Exposure tab
saltastroops/nir-simulator pull request #11
Opened 2023-10-24 07:03 UTC by Eb-Zeero

2023-10-24 17:00 UTC, hettlage requested changes
> Reviewed 20 of 20 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 24 unresolved discussions (waiting on @Eb-Zeero)

___
*[`backend/backend/modules/exposure.py` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXbfHD-nPzKVJV1fZu:-NhXbfHD-nPzKVJV1fZv:b-dsxp1b) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/backend/backend/modules/exposure.py#L1)):*
> ```Python
> import csv
> ```

Will be reviewed at a later point in time.
___
*[`backend/backend/modules/exposure.py` line 203 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXbTTYClLIbUydo98h:-NhXbTTYClLIbUydo98i:b-8zpyp1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/backend/backend/modules/exposure.py#L203)):*
> ```Python
> # Function to load galaxy data for different types and scenarios
> def load_galaxy_data() -> List[Tuple[str, str, bool, Galaxy]]:
>     return [
> ```

Can't you just construct the filename...?
___
*[`react/src/components/Simulator.tsx` line 60 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXc1QI63pciJgJyLtG:-NhXc1QI63pciJgJyLtH:b8gjaso) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/Simulator.tsx#L60)):*
> ```XML
>       instrumentConfiguration: this.instrumentConfiguration.data(),
>       exposureConfiguration: this.exposureConfiguration.data,
>       // exposureConfiguration: {
> ```

I guess the commented out code can be deleted?
___
*[`react/src/components/Simulator.tsx` line 178 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXZnj80BWrF2wa2rgm:-NhXZnj94HnXT4e_4XuS:bexey3j) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/Simulator.tsx#L178)):*
> ```XML
>       <div ref={exposureDivRef} style={{ display: "none" }}>
>         <ExposurePanel
>           setupData={setup.data()}
> ```

You have to pass `step` rather than `setup.data()` as you need the user input rather than the parsed values.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 5 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhX_7q90OOR_AenWzee:-NhX_7q90OOR_AenWzef:bn8li2g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/ExposurePanel.tsx#L5)):*
> ```XML
> import { SolvingTabs } from "./solve-section/SolvingTabs.tsx";
> 
> export interface GainType {
> ```

Even if it is only for consistency, I'd keep the types with the component class files.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 11 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhX_Ssc9tgBbRjBzJtT:-NhX_Ssc9tgBbRjBzJtU:b69ygfv) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/ExposurePanel.tsx#L11)):*
> ```XML
>   fullWell: string;
> }
> export class Gain {
> ```

Here and elsewhere: error handling is missing.
___
*[`react/src/components/exposure/gain-panel/BrightObject.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXT0de-j4fo7jq5quq:-NhXT0de-j4fo7jq5qur:b-4dcnla) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/BrightObject.tsx#L1)):*
> ```XML
> export function BrightObject() {
> ```

`BrightObject` and `FaintObject` are the same really (namely something like `NonEditableGainPanel`.

At any rate, you should pass the values rather than hardcoding them.
___
*[`react/src/components/exposure/gain-panel/BrightObject.tsx` line 8 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTg43-1WnzhEKYloy:-NhXTg43-1WnzhEKYloz:b-n0rdk3) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/BrightObject.tsx#L8)):*
> ```XML
>       </div>
>       <div className="columns">
>         <div className="column ">Read Noice: </div>
> ```

Noice > Noise
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 25 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTiRe8ANugS4AA34U:-NhXTiRe8ANugS4AA34V:b-n0rdk3) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/CustomObject.tsx#L25)):*
> ```XML
>       </div>
>       <div className="columns">
>         <div className="column">Read Noice: </div>
> ```

Noice > Noise
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 52 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTZLl704HI7xUKvUV:-NhXTZLl704HI7xUKvUW:b-4bjv2y) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/CustomObject.tsx#L52)):*
> ```XML
>         </div>
>       </div>
>     </div>
> ```

Errors aren't shown.
___
*[`react/src/components/exposure/gain-panel/FaintObject.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTb_p0aq3udLTnxmX:-NhXTb_p0aq3udLTnxmY:b-kiushl) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/FaintObject.tsx#L1)):*
> ```XML
> export function FaintObject() {
> ```

See comment on BrightObject.
___
*[`react/src/components/exposure/gain-panel/FaintObject.tsx` line 8 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTkzHCd0KeK30exrp:-NhXTkzHCd0KeK30exrq:b-n0rdk3) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/FaintObject.tsx#L8)):*
> ```XML
>       </div>
>       <div className="columns">
>         <div className="column">Read Noice: </div>
> ```

Noice > Noise
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXU2N58T6NEQ22JX5y:-NhXU2N58T6NEQ22JX5z:b5bq86g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L7)):*
> ```XML
> import { Gain, GainType } from "../ExposurePanel.tsx";
> 
> export function GainPanel({ setupData, update }: any) {
> ```

I don't think this type should be `any`.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTywuCo5-FDpKmNzv:-NhXTywuCo5-FDpKmNzw:bkcr76k) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
> ```XML
>   const updateGain = (gainValues: GainType) => {
>     update({
>       ...setupData,
> ```

Why do you pass r
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXU99NBJk3Fh2e-Tac:-NhXU99NBJk3Fh2e-Tad:b5bq86g) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L1)):*
> ```XML
> export function GainTypeSelector({ updateGain, gainType }: any) {
> ```

I don't think this type should be `any`.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 4 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXUmBu7CbuziIsXQBI:-NhXUmBu7CbuziIsXQBJ:b-9ygpri) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/com [...]

2023-10-26 09:19 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 24 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 5 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhX_7q90OOR_AenWzee:-NhfGybX9kvUXCEDF97g:bntv0mg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/ExposurePanel.tsx#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Even if it is only for consistency, I'd keep the types with the component class files.
</blockquote></details>

please explain.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 11 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhX_Ssc9tgBbRjBzJtT:-NheoR8rEg3lQCHkGsk8:b-v3imqg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/ExposurePanel.tsx#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Here and elsewhere: error handling is missing.
</blockquote></details>

I do not know the limits of inputs
___
*[`react/src/components/exposure/gain-panel/BrightObject.tsx` line 1 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXT0de-j4fo7jq5quq:-Nheoh-REg11MOK-ykku:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/BrightObject.tsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

`BrightObject` and `FaintObject` are the same really (namely something like `NonEditableGainPanel`.

At any rate, you should pass the values rather than hardcoding them.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 7 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXU2N58T6NEQ22JX5y:-Nhes1Bl7jeFgW5ay5Jh:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L7)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this type should be `any`.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTywuCo5-FDpKmNzv:-Nhes6CM4EhjPsL7wrls:b-w4wds4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why do you pass r
</blockquote></details>

do not understand this?
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 21 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXUvyFD3_HAF18UUWd:-NhesD5a253y0gcz6rVw:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this value should be `any`.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 22 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXV3IR6bZup5lHvU4m:-NhesWqs3mIpEItnMmwz:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why "updateSource" rather than, say, "newGain" or "newGainValues" or something like that?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 22 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXUJNq6vVivLQ-TfmF:-NhesXgX42UbCtScSVt5:bpila1k) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

An if or switch statement might be clearer.
</blockquote></details>

I fo not understand this
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 3 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhX_vfH2501CKLhWoyI:-Nheu7rc5z3BulkVRsLQ:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this type should be `any`.

(I'll stop explicitly noting it, so just assume I say it everywhere where `any`occirs. I'm happy to discuss this.)
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 15 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXasWN7RAhde2zrQ9B:-NhfGv3sBuR73PFT8_K8:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L15)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This can be simplified by passing the target value rather than the event.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 26 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXaaUJBPKPi6pFX3D7:-NheuwA7EpcFEoaczkRL:b9vnzp4) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I suspect the `updatePlot` function cannot be defined here.
</blockquote></details>

it should as the update button is in this component...
it should call the updatePlot method from a parent 
for now ignore as the update plot method does not exist yet
___
*[`react/src/components/exposure/solve-section/SolvingTabs.tsx` line 25 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXX23l7q_CIFoT4FHu:-NhewY2GAZ9dXFRNp7uj:bmmvacg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolvingTabs.tsx#L25)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think state handling can be simplified, in particular if you keep the exposure/SNR configuration local (as you do -- I'm in two minds about that one).

Thinking about it, I believe handling state might need some discussion.
</blockquote></details>

yes, please
___
*[`react/src/components/exposure/solve-section/SolvingTabs.tsx` line 37 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXXUtaEfkrHcTJvYeR:-Nhf5tqj1U_TjfvyV2c5:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolvingTabs.tsx#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I don't think this type should be `any`.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-26 10:19 UTC, hettlage requested changes
> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 29 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 68 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfRE-L1IKzf5oxdQMT:-NhfRE-L1IKzf5oxdQMU:b-d9rv3o) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L68)):*
> ```XML
> export class SolveSNR {
>   public exposureTime = "3600";
>   public detectorIterations = "1";
> ```

Why would this be defined only for solving for the SNR?

Also, can we discuss the "exposure types"?
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 107 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfQniO0OvmMDrNGxnN:-NhfQniO0OvmMDrNGxnO:ba6h9ye) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L107)):*
> ```XML
> }
> 
> export interface ExposureConfigurationType {
> ```

Can we discuss this, please?
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfS1oLBRCJbF7bi-Lk:-NhfS1oLBRCJbF7bi-Ll:be3zjy1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/CustomObject.tsx#L3)):*
> ```XML
> import { GainType } from "../ExposurePanel.tsx";
> 
> type Params = {
> ```

Params > Props
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTywuCo5-FDpKmNzv:-NhfUdcGALMu-5yoxVZ5:bju7u9u) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

do not understand this?
</blockquote></details>

Must have benenn a mistake. Sorry.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJPbC9HOjdGhcN5jY:-NhfJPbDD4VJDuHkL4Fo:be3zjy1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
> ```XML
> } from "../ExposurePanel.tsx";
> 
> type Params = {
> ```

Params > Props
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJdcI5DXHQ6qn0RBv:-NhfJdcI5DXHQ6qn0RBw:bemvmzr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L1)):*
> ```XML
> import { GainType } from "../ExposurePanel.tsx";
> ```

Can we talk about the way of handling gains?
___
*[`react/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJsLt8CfMdkLzUNft:-NhfJsLt8CfMdkLzUNfu:be3zjy1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L3)):*
> ```XML
> import { GainType } from "../ExposurePanel.tsx";
> 
> interface Params {
> ```

Params > Props
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfPymG9-dg8m2Riegs:-NhfPymH-EDx7zLiqka_:bmqtodq) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L3)):*
> ```XML
> import { ExposureConfigurationType, Sampling } from "../ExposurePanel.tsx";
> 
> type Params = {
> ```

We should agree on using `type` or `interface` for props.

Params > Props
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 26 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXaaUJBPKPi6pFX3D7:-NhfT9qm4kAVOlVf4LNL:bw63w0l) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L26)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

it should as the update button is in this component...
it should call the updatePlot method from a parent 
for now ignore as the update plot method does not exist yet
</blockquote></details>

Fair point.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 11 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfK9rI8KJD6rZvn6i4:-NhfK9rI8KJD6rZvn6i5:bku15bb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L11)):*
> ```XML
>   const [wavelengthType, setWavelengthType] = useState("central");
> 
>   const wavelengthTypeChange = (targetValue: string) => {
> ```

You could choose a more meaningful name, such as wavelengthType. :-)

Can we discuss the handling of wavelength types?
___
*[`react/src/components/exposure/solve-section/SolveForSNR.tsx` line 4 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfLPQDBDYi0tZk12A6:-NhfLPQDBDYi0tZk12A7:be3zjy1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForSNR.tsx#L4)):*
> ```XML
> import { SimulationSetupParameters } from "../../Simulator.tsx";
> 
> type Params = {
> ```

Params > Props
___
*[`react/src/components/exposure/solve-section/SolveForSNR.tsx` line 5 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfLWd12CYWrJ1CRKHh:-NhfLWd12CYWrJ1CRKHi:b-lior6r) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForSNR.tsx#L5)):*
> ```XML
> 
> type Params = {
>   setupData: SimulationSetupParameters;
> ```

setupData > setup


<!-- Sent from Reviewable.io -->

2023-10-30 13:58 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: 11 of 22 files reviewed, 29 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 68 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfRE-L1IKzf5oxdQMT:-Ni-sFvPBbtLWCY1cC-Q:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L68)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Why would this be defined only for solving for the SNR?

Also, can we discuss the "exposure types"?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 107 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfQniO0OvmMDrNGxnN:-Ni-eZwV5YyOxcllo92G:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L107)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we discuss this, please?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfS1oLBRCJbF7bi-Lk:-Nhfj5JmAUMPhZuwi2sh:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/CustomObject.tsx#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Params > Props
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXTywuCo5-FDpKmNzv:-Nhfj9G03-Ei7AAvQwbK:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Must have benenn a mistake. Sorry.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 10 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJPbC9HOjdGhcN5jY:-Nhfj7GZ0DJ__LaAaxxd:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainPanel.tsx#L10)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Params > Props
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJdcI5DXHQ6qn0RBv:-Ni-fLwl0VZatM-K5CGF:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Can we talk about the way of handling gains?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/NonEditableGainPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfJsLt8CfMdkLzUNft:-NhfjJkB1Na9Mfu_SBBK:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/NonEditableGainPanel.tsx#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Params > Props
</blockquote></details>

Done.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfPymG9-dg8m2Riegs:-NhfjKYwDWmaXvLW-w5f:bn41ec2) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

We should agree on using `type` or `interface` for props.

Params > Props
</blockquote></details>

Done. Type it is
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 26 at r1](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhXaaUJBPKPi6pFX3D7:-Ni-fR5d0hLRQpX39sXF:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/877f2dc39530042c2b6d3cf9b100c3b61ebcbea9/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L26)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Fair point.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 11 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfK9rI8KJD6rZvn6i4:-Ni-fQC23wlNHnNaINbY:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L11)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

You could choose a more meaningful name, such as wavelengthType. :-)

Can we discuss the handling of wavelength types?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForSNR.tsx` line 4 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfLPQDBDYi0tZk12A6:-NhfjWjl6qXhwIusWdPt:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForSNR.tsx#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Params > Props
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForSNR.tsx` line 5 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfLWd12CYWrJ1CRKHh:-Ni-sD---0ld8KPuFkKI:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/solve-section/SolveForSNR.tsx#L5)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

setupData > setup
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-10-31 09:54 UTC, hettlage requested changes
> Reviewed 2 of 9 files at r3, 9 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 31 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/Error.tsx` line 4 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3gkHfCfMSoPuPBIsE:-Ni3gkHfCfMSoPuPBIsF:b-g7sfcb) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/Error.tsx#L4)):*
> ```XML
>   error: string;
> }
> export function Error({ error }: Props) {
> ```

The component seems to be used nowhere.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3gsc6C_hEp_woT_-n:-Ni3gsc6C_hEp_woT_-o:bqyazc9) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L1)):*
> ```XML
> import { GainPanel } from "./gain-panel/GainPanel.tsx";
> ```

I'm afraid we should chat about the types again.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hBqO-hbpXVKNZKAe:-Ni3hBqO-hbpXVKNZKAf:b-8ltkqm) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/ExposurePanel.tsx#L44)):*
> ```XML
> }
> 
> export function ExposurePanel({ setupData, update }: any) {
> ```

Should not be `any`.
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hUYy0XledDr7atJz:-Ni3hUYy0XledDr7atK-:baivbkk) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/CustomObject.tsx#L1)):*
> ```XML
> import { GainType } from "../ExposurePanel.tsx";
> ```

Shouldn't the component be called `CustomGain` rather?
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 6 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3iC0B70KTu48N_EaI:-Ni3iC0B70KTu48N_EaJ:bl1nkgz) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L6)):*
> ```XML
> import { ExposureConfigurationType } from "../ExposurePanel.tsx";
> 
> export type GainType = {
> ```

There is still inconsistency between the naming of these types in different directories.

Also, do you have to export the type?
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 13 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hrpc9Neff8HQzac6:-Ni3hrpc9Neff8HQzac7:b-gjdk7o) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L13)):*
> ```XML
> };
> export class Gain {
>   public gainType: "Faint Object" | "Bright Object" | "Custom Object" =
> ```

I think the gain type should be Faint, Bright or Custom.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 30 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3ihqS5POuYV5U7Gqw:-Ni3ihqS5POuYV5U7Gqx:b-gph2qn) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L30)):*
> ```XML
>   public get data() {
>     return {
>       adu: parseFloat(this.adu),
> ```

Isn't add an integer?
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 32 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3ifBVBXMPPjyr-yAa:-Ni3ifBW7rmdHnajBjz0:b50e3s5) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L32)):*
> ```XML
>       adu: parseFloat(this.adu),
>       readNoise: parseFloat(this.readNoise),
>       fullWell: parseFloat(this.fullWell),
> ```

Isn't fullWell an integer?
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3j-vz0zT4HleqDZee:-Ni3j-w-9NDVIIRNpkIA:b-lwxufg) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L44)):*
> ```XML
> 
>     if (Number.isNaN(adu) || !Number.isInteger(adu) || adu < minAdu) {
>       errors.adu = `The electron/ADU must be a positive integer greater than or equal to ${minAdu}.`;
> ```

Probably: electron/ADU > ADU

a positive integer > an integer
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 52 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3jSZ_0kPHEGuBeuIE:-Ni3jSZ_0kPHEGuBeuIF:b-5tia75) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L52)):*
> ```XML
>     if (
>       Number.isNaN(readNoise) ||
>       !Number.isInteger(readNoise) ||
> ```

The read noise is a float, not an integer.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 66 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3jdwY7qt6WoghwuY9:-Ni3jdwY7qt6WoghwuYA:b-exk572) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L66)):*
> ```XML
>       fullWell < minFullWell
>     ) {
>       errors.fullWell = `The full well must be a positive integer greater than or equal to ${minFullWell}.`;
> ```

a positive integer > an integer
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 9 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3oz7P0QiynrsneUTL:-Ni3oz7P0QiynrsneUTM:b-akfnjc) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L9)):*
> ```XML
> 
> export function GainTypeSelector({ updateGain, gainType }: Params) {
>   const faintObjectDefaults: GainType = {
> ```

faintObjectDefaults > faintGain or faintDefaults
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 29 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3om0Q9wgwPzhxofFF:-Ni3om0Q9wgwPzhxofFG:bax2dbu) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L29)):*
> ```XML
>   };
>   const update = (
>     value: "Faint Object" | "Bright Object" | "Custom Object",
> ```

Probably Faint rather than FaintObject etc.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfPymG9-dg8m2Riegs:-Ni3qdCMB3tpZLX75BHk:b-2td8o0) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L3)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done. Type it is
</blockquote></details>

But in other directories `interface Props` is used...
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 20 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3post2TJZnY4xAb1K:-Ni3post2TJZnY4xAb1L:bck5221) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L20)):*
> ```XML
>   public get data() {
>     return {
>       numberOfSamples: parseFloat(this.numberOfSamples),
> ```

numberOfSamples is an inte [...]

2023-10-31 11:11 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 31 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/Error.tsx` line 4 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3gkHfCfMSoPuPBIsE:-Ni4M7pO3gsiMXx0625d:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/Error.tsx#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The component seems to be used nowhere.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hBqO-hbpXVKNZKAe:-Ni4EDJKDUsjvmk0Hnnp:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/ExposurePanel.tsx#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Should not be `any`.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hUYy0XledDr7atJz:-Ni4EXtC4mqY79pSunDm:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/CustomObject.tsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Shouldn't the component be called `CustomGain` rather?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 13 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3hrpc9Neff8HQzac6:-Ni4Fbux7ZZL-RCPiTew:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L13)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I think the gain type should be Faint, Bright or Custom.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 30 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3ihqS5POuYV5U7Gqw:-Ni4Fp5LE2cIhiFkWbqM:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't add an integer?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 32 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3ifBVBXMPPjyr-yAa:-Ni4FpSL0qukxpXPyZUa:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L32)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Isn't fullWell an integer?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3j-vz0zT4HleqDZee:-Ni4Fw11EvYP0has6L-q:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably: electron/ADU > ADU

a positive integer > an integer
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 52 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3jSZ_0kPHEGuBeuIE:-Ni4G5M79hdf1NSloPr5:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L52)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The read noise is a float, not an integer.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 66 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3jdwY7qt6WoghwuY9:-Ni4GE0cEbyDE_k6jesQ:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a positive integer > an integer
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 9 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3oz7P0QiynrsneUTL:-Ni4Gd9NBlKMKnQBEaBx:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

faintObjectDefaults > faintGain or faintDefaults
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 29 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3om0Q9wgwPzhxofFF:-Ni4HQvj5joImFk2cWS1:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Probably Faint rather than FaintObject etc.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 3 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NhfPymG9-dg8m2Riegs:-Ni4IfOM02TrQpfI_Ruy:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L3)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

But in other directories `interface Props` is used...
</blockquote></details>

Done.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 20 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3post2TJZnY4xAb1K:-Ni4HYVX96O-EeqWqAi_:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L20)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

numberOfSamples is an integer.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 4 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni441VX23IRYA-6aytN:-Ni4Kd-g5_9q03nihyQE:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L4)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better SNRType?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 9 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni4451c4dJISbXVK9oh:-Ni4IzHL6Uykv7ijo7Rz:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/solve-section/SolveForExposureTime.tsx#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Maybe better ExposureTimeQuery?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 10 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3qsa5AtJrqRwGQGWg:-Ni4J57k-M1VToXXYb8L:b-896fix) ([raw file](https://github.com/saltastroo [...]

2023-10-31 14:16 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: 11 of 22 files reviewed, 31 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 1 at r2](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3gsc6C_hEp_woT_-n:-Ni55-OdBP0DW4Lu2RN3:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/69c6e90d6db226b5e7e18c8d9efcfff0516e5f71/react/src/components/exposure/ExposurePanel.tsx#L1)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'm afraid we should chat about the types again.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 6 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3iC0B70KTu48N_EaI:-Ni54_j6CtTDplw-Mplm:b-2t8a5a) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L6)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

There is still inconsistency between the naming of these types in different directories.

Also, do you have to export the type?
</blockquote></details>

there is this exception
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 37 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3pU2o-i6N9SqTN_jl:-Ni54lKT9Xmj09QaZDiM:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L37)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

a positive integer > an integer

We should double-check limits with Moses. If the minimum is 1, the error message should read "must be a positive integer"
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForSNR.tsx` line 62 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni45fOZ12wAHcvUDwcT:-Ni54yJ7Ejd3oH59zviV:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/solve-section/SolveForSNR.tsx#L62)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

newSetup > exposureConfiguration

Also, we might discuss the type to pass.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolvingTabs.tsx` line 9 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni47P_-8funYLoMsn_V:-Ni54oFC9YzDOi0GvSox:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/solve-section/SolvingTabs.tsx#L9)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

newSetup > exposureConfiguration

Also, we might discuss the type to pass.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-01 12:57 UTC, hettlage requested changes
> Reviewed 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 16 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 30 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni90lR17ng1dMO9X6s2:-Ni90lR17ng1dMO9X6s3:b-dd5x92) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/ExposurePanel.tsx#L30)):*
> ```XML
>   }
> 
>   public get data() {
> ```

This object currently includes both `exposureTime` and `snr`, but didn't we say that only the relevant one should be included?
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3j-vz0zT4HleqDZee:-Ni9wxIz78_VQIzIF5hn:b4l8mnu) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L44)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It still reads "positive integer".
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 39 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9oXcJ-UiIEHNuMbAu:-Ni9oXcJ-UiIEHNuMbAv:bqdf9av) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L39)):*
> ```XML
>       !Number.isInteger(numberOfSamples)
>     ) {
>       errors.numberOfSamples = `Must be a positive integer.`;
> ```

Given the error message I think you should not use a variable `minExposureTime`, but explicitly compare against 0, `exposureTime < 0`.

Also, in line with other error messages, you should name the property: "The number of samples must be a positive integer."
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 54 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9oopo28EVg9a-65Hp:-Ni9oopo28EVg9a-65Hq:bpsfn42) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L54)):*
> ```XML
>   update: (setupData: ExposureConfiguration) => void;
> }
> export function SamplingPanel({ setupData, update }: Props) {
> ```

I'd suggest to call `setupData` `sampling` instead.

(Analogous comments apply to other component functions, even of not explicitly mentioned in this review.)
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 66 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9wI-wEM3TWzQwMYwr:-Ni9wI-wEM3TWzQwMYws:buwkgh2) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/CustomObject.tsx#L66)):*
> ```XML
>         <div className="column pb-0">Full Well: </div>
>         <div className="column pb-0">
>           <div className="control">
> ```

The input field for the full well is too short; some of the input is hidden.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 22 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9szYNBisR3Afqap6p:-Ni9szYNBisR3Afqap6q:b-2avhxz) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L22)):*
> ```XML
>   };
> 
>   const customObjectDefaults: GainType = {
> ```

I'd suggest you don't set defaults for the custom gain, but rather keep whatever values you currently have.
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 28 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni92yZi3b5aTo8vnR8a:-Ni92yZi3b5aTo8vnR8b:b-web57f) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L28)):*
> ```XML
>     const data = this.data;
> 
>     // Detector Iterations
> ```

Wrong comment; should be `// Wavelength`
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 40 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni92ajI4iwjPMeZE9bc:-Ni92ajI4iwjPMeZE9bd:b-1i4gor) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L40)):*
> ```XML
>     }
> 
>     // Exposure Time
> ```

Wrong comment; should be `// SNR`
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 56 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9o2hG5_ZU5xVTAiDh:-Ni9o2hG5_ZU5xVTAiDi:b13w156) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L56)):*
> ```XML
> 
> interface Props {
>   setupData: SNR;
> ```

I would suggest to call `setupData` `snr` instead.
___
*[`react/src/components/exposure/query-panel/QueryTabs.tsx` line 29 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9wc1d3YQ7u4e8q89E:-Ni9wc1d3YQ7u4e8q89F:bysmfzm) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/QueryTabs.tsx#L29)):*
> ```XML
>   return (
>     <>
>       <div className="tabs is-boxed">
> ```

Some of the text in the Exposure time tab rider is cropped.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 21 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9jUQ9C3FTwdkpB-x2:-Ni9jUQ9C3FTwdkpB-x3:bozl3dn) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L21)):*
> ```XML
>     return {
>       singleExposureTime: parseFloat(this.singleExposureTime),
>       detectorIterations: parseInt(this.detectorIterations),
> ```

It might be safer to explicitly set the radix to 10: `parseInt(..., 10)`. Quoting from the documentation: If 0 or not provided, the radix will be inferred based on string's value. Be careful — this does not always default to 10!

The same applies to all uses of `parseInt`.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 44 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9mjlUEuiSD9-L786d:-Ni9mjlUEuiSD9-L786e:b-kda20z) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L44)):*
> ```XML
>     const minExposureTime = 0;
>     if (Number.isNaN(exposureTime) || exposureTime < minExposureTime) {
>       errors.singleExposureTime = "Exposure time must be a positive number.";
> ```

Exposure > The exposure

Given the error message I think you should not use a variable `minExposureTime`, but explicitly compare against 0, `exposureTime < 0`.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 56 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9nTk45j229-BHOYud:-Ni9nTk5EJn_napMPtPa:b-gkhf53) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L56)):*
> ```XML
> 
> interface Props {
>   setupData: ExposureTime;
> ```

I would suggest to call `setupData` `exposureTime` instead.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 1 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni91xC-8UIM4rtCFmmT:-Ni91xC-8UIM4rtCFmmU:byir8qj) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2 [...]

2023-11-01 14:50 UTC, Eb-Zeero reviewed
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 16 unresolved discussions (waiting on @hettlage)

___
*[`react/src/components/exposure/ExposurePanel.tsx` line 30 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni90lR17ng1dMO9X6s2:-NiA5jSKEL5wi8pSozo0:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/ExposurePanel.tsx#L30)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

This object currently includes both `exposureTime` and `snr`, but didn't we say that only the relevant one should be included?
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainPanel.tsx` line 44 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni3j-vz0zT4HleqDZee:-NiAA66_054OOrOsdw3G:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainPanel.tsx#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It still reads "positive integer".
</blockquote></details>

Done.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 39 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9oXcJ-UiIEHNuMbAu:-NiAKrxL4OWSrWZrw9tH:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L39)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Given the error message I think you should not use a variable `minExposureTime`, but explicitly compare against 0, `exposureTime < 0`.

Also, in line with other error messages, you should name the property: "The number of samples must be a positive integer."
</blockquote></details>

Done.
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 54 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9oopo28EVg9a-65Hp:-NiALuAlD7V2w8rw6E8T:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L54)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest to call `setupData` `sampling` instead.

(Analogous comments apply to other component functions, even of not explicitly mentioned in this review.)
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/CustomObject.tsx` line 66 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9wI-wEM3TWzQwMYwr:-NiA9y-gA1oGtLb8ORKq:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/CustomObject.tsx#L66)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

The input field for the full well is too short; some of the input is hidden.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/gain-panel/GainTypeSelector.tsx` line 22 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9szYNBisR3Afqap6p:-NiAC2oS9KqRkAPvL98p:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e3c548abdd/react/src/components/exposure/gain-panel/GainTypeSelector.tsx#L22)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I'd suggest you don't set defaults for the custom gain, but rather keep whatever values you currently have.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 28 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni92yZi3b5aTo8vnR8a:-NiACc1F1ri_g_vlrlJa:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L28)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong comment; should be `// Wavelength`
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 40 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni92ajI4iwjPMeZE9bc:-NiACiR-4R5ujKJIyP8w:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L40)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Wrong comment; should be `// SNR`
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 56 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9o2hG5_ZU5xVTAiDh:-NiADDNG0h8HcdKrib38:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to call `setupData` `snr` instead.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/QueryTabs.tsx` line 29 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9wc1d3YQ7u4e8q89E:-NiAJC98CfhaM5kl1T4J:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/QueryTabs.tsx#L29)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Some of the text in the Exposure time tab rider is cropped.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 21 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9jUQ9C3FTwdkpB-x2:-NiAJjU97vLxEeqV8VrF:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L21)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

It might be safer to explicitly set the radix to 10: `parseInt(..., 10)`. Quoting from the documentation: If 0 or not provided, the radix will be inferred based on string's value. Be careful — this does not always default to 10!

The same applies to all uses of `parseInt`.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 44 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9mjlUEuiSD9-L786d:-NiAK-dp0_3upxR_pXwu:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L44)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

Exposure > The exposure

Given the error message I think you should not use a variable `minExposureTime`, but explicitly compare against 0, `exposureTime < 0`.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 56 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9nTk45j229-BHOYud:-NiAK7yR2Wxb0cdfwd3_:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L56)):*
<details><summary><i>Previously, hettlage wrote…</i></summary><blockquote>

I would suggest to call `setupData` `exposureTime` instead.
</blockquote></details>

Done.
___
*[`react/src/components/exposure/solve-section/SolveForExposureTime.tsx` line 1 at r4](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni91xC-8UIM4rtCFmmT:-NiACWKQEdMt-QSzLNvS:b-896fix) ([raw file](https://github.com/saltastroops/nir-simulator/blob/3e7f00d2a82175c573993605446116e [...]

2023-11-02 10:11 UTC, hettlage requested changes
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/saltastroops/nir-simulator/11)* status: all files reviewed, 11 unresolved discussions (waiting on @Eb-Zeero)

___
*[`react/src/components/Simulator.tsx` line 146 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiER4X28A4OB27V7E_k:-NiER4X28A4OB27V7E_l:bmf47e1) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/Simulator.tsx#L146)):*
> ```XML
>       <div ref={exposureDivRef} style={{ display: "none" }}>
>         <ExposurePanel
>           setupData={setup}
> ```

I'd avoid "data" and keep it to "setup".
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 21 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiERS0f7RxHkUzcOMeA:-NiERS0f7RxHkUzcOMeB:b-klnitw) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/ExposurePanel.tsx#L21)):*
> ```XML
>   snr: SNR;
> }
> type ExposureConfigurationData = {
> ```

Now this is where I would have agreed that typing it might be more pain than gain...
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 50 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiERn_4CvxeNufriAPo:-NiERn_4CvxeNufriAPp:b5timpj) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/ExposurePanel.tsx#L50)):*
> ```XML
>     };
> 
>     if (this.activeQuery === "SNR") {
> ```

Easier:

data.snr = this.snr.data
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 54 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiERuNJ4v1kc0UI3VzF:-NiERuNJ4v1kc0UI3VzG:b-f0wy6v) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/ExposurePanel.tsx#L54)):*
> ```XML
>     }
>     if (this.activeQuery === "ExposureTime") {
>       data = { ...data, exposureTime: this.exposureTime.data };
> ```

Easier: data.exposureTime = this.exposureTime.data
___
*[`react/src/components/exposure/ExposurePanel.tsx` line 62 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiES80o4Hb-DX9j3kTa:-NiES80o4Hb-DX9j3kTb:b8hsqci) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/ExposurePanel.tsx#L62)):*
> ```XML
> 
> interface Props {
>   setupData: SimulationSetup;
> ```

I'd avoid the "data" and stick to "setup".
___
*[`react/src/components/exposure/sampling-panel/SamplingPanel.tsx` line 54 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9oopo28EVg9a-65Hp:-NiEV9qQ65h5GUaT3uxK:bfxptwc) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/sampling-panel/SamplingPanel.tsx#L54)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Hmm, true, the name of the variable should be `exposureTime`. But it raises the question why you are passing the exposure time rather than the sampling?
___
*[`react/src/components/exposure/gain-panel/CustomGainPanel.tsx` line 1 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiEVmUr6WJs8fR9KkdN:-NiEVmUr6WJs8fR9KkdO:bty2i75) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/gain-panel/CustomGainPanel.tsx#L1)):*
> ```XML
> import { Gain } from "./GainPanel.tsx";
> ```

The layout is broken.

![screenshot\_388.png](https://files.reviewableusercontent.io/images/reviewable/11633365/RLHLIg3IzWOezO7DSas06vk0/screenshot_388.png)
___
*[`react/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx` line 46 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiETtQw8PJLnOcwApS8:-NiETtQw8PJLnOcwApS9:bnjt7a6) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx#L46)):*
> ```XML
>     }
> 
>     // NR
> ```

NR > SNR
___
*[`react/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx` line 101 at r6](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiEU7PN-x-RuyqhlKq2:-NiEU7PN-x-RuyqhlKq3:btmxkg5) ([raw file](https://github.com/saltastroops/nir-simulator/blob/6d7e7653c2668a097b11a6d655f79f95f4723572/react/src/components/exposure/query-panel/ExposureTimeQueryTab.tsx#L101)):*
> ```XML
> 
>       <div className="field">
>         <label className="label">Wavelength</label>
> ```

I think there should be only one label for the wavelength.
___
*[`react/src/components/exposure/query-panel/ExposureTimeTab.tsx` line 44 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-NiETz3IAwvjy9HCkJJq:-NiETz3IAwvjy9HCkJJr:b-exk572) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/ExposureTimeTab.tsx#L44)):*
> ```XML
>     const minSnr = 1;
>     if (Number.isNaN(snr) || snr < minSnr || !Number.isInteger(snr)) {
>       errors.snr = `The requested signal to noise must be a positive integer greater than or equal to ${minSnr}.`;
> ```

a positive integer > an integer
___
*[`react/src/components/exposure/query-panel/SNRTab.tsx` line 44 at r5](https://reviewable.io/reviews/saltastroops/nir-simulator/11#-Ni9mjlUEuiSD9-L786d:-NiEUVJ-6i-cQ8XgFr8w:b-lerucr) ([raw file](https://github.com/saltastroops/nir-simulator/blob/2edcb23c06fe36e1b65370624bb1fa2814907de1/react/src/components/exposure/query-panel/SNRTab.tsx#L44)):*
<details><summary><i>Previously, Eb-Zeero (Nhlavutelo Macebele) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I'd argue that the second half is not done... :-/


<!-- Sent from Reviewable.io -->

2023-11-02 21:31 UTC, merged